import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../componets/footer/Footer";
import AuthProvider from "@/context/AuthProvider";
import NavBar from "@/componets/navbar/Navbar";
import QueryProvider from "@/Utility/QueryProvider";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <NavBar />
            {children}

            <Footer />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
