import "./globals.css";
import Footer from "../componets/footer/Footer";
import AuthProvider from "@/context/AuthProvider";
import NavBar from "@/componets/navbar/Navbar";
import QueryProvider from "@/Utility/QueryProvider";
import { Inter } from "next/font/google";
import RouteLoader from "@/Utility/RouterLoader";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Doner Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://img.icons8.com/bubbles/100/drop-of-blood.png"
        />
      </head>
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <NavBar />
            <RouteLoader />
            {children}

            <Footer />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
